#!/usr/bin/env bash
#
# gpmdp - get info from Google Play Music Desktop Player easily
# https://github.com/iandrewt/gpmdp-bash
#
# Created by Andrew Titmuss
# https://github.com/iandrewt/

# Speed up script by not using Unicode
export LC_ALL=C
export LANG=C

# Determine config file location from uname
case "$(uname)" in
    "Linux" | *"BSD") json_file="$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" ;;
    "Darwin") json_file="$HOME/Library/Application Support/Google Play Music Desktop Player/json_store/playback.json" ;;
    "CYGWIN"*) json_file="%APPDATA%/Google Play Music Desktop Player/json_store/playback.json" ;;
esac

title () {
    title=$(awk -F '"|:' '/title/ {printf $5}' "$json_file")
    printf "${title}"
}

artist () {
    artist=$(awk -F '"|:' '/artist/ {printf $5}' "$json_file")
    printf "${artist}"
}

album () {
    album=$(awk -F '"|:' '!/albumArt/ && /album/ {printf $5}' "$json_file")
    printf "${album}"
}

album_art () {
    album_art=$(awk -F '"|:' '/albumArt/ {printf $5":"$6}' "$json_file")
    printf "${album_art}"
}

time_current () {
    time_current=$(awk -F ': |,' '/current/ {printf $2}' "$json_file")
    printf "${time_current}"
}

time_total () {
    time_total=$(awk -F ': |,' '/total/ {printf $2}' "$json_file")
    printf "${time_total}"
}

gpmdp_status () {
    gpmdp_status=$(awk -F ': |,' '/playing/ {printf $2}' "$json_file")

    if [[ "$gpmdp_status" == *"true"* ]]; then
        gpmdp_status="Playing"
    elif [[ "$gpmdp_status" == *"false"* ]]; then
        gpmdp_status="Paused"
    fi

    printf "${gpmdp_status}"
}

gpmdp_info () {
    if [ "$(gpmdp_status)" == "Playing" ]; then
        printf "Now Playing: $(title) by $(artist)"
    elif [ "$(gpmdp_status)" == "Paused" ]; then
        printf "Paused: $(title) by $(artist)"
    fi
    return
}

current () {
    printf "$(artist) - $(title)"
}

usage () { cat << EOF

    usage: gpmdp <option>

    info            Print info about now playing song
    title           Print current song title
    artist          Print current song artist
    album           Print current song album
    album_art       Print current song album art URL
    time_current    Print current song time in milliseconds
    time_total      Print total song time in milliseconds
    status          Print whether GPMDP is paused or playing
    current         Print now playing song in "artist - song" format
    help            Print this help message

EOF
exit 1
}


case $1 in
    info) gpmdp_info ;;
    title) title ;;
    artist) artist ;;
    album) album ;;
    album_art) album_art ;;
    time_current) time_current ;;
    time_total) time_total ;;
    status) gpmdp_status ;;
    current) current ;;
    *) usage ;;
esac

